// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: AISnapshotEntitySkillCycle.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace NewProtos {

  /// <summary>Holder for reflection information generated from AISnapshotEntitySkillCycle.proto</summary>
  public static partial class AISnapshotEntitySkillCycleReflection {

    #region Descriptor
    /// <summary>File descriptor for AISnapshotEntitySkillCycle.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AISnapshotEntitySkillCycleReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiBBSVNuYXBzaG90RW50aXR5U2tpbGxDeWNsZS5wcm90byKVAQoaQUlTbmFw",
            "c2hvdEVudGl0eVNraWxsQ3ljbGUSGwoTVW5rMzMwMF9JSU9JQkxFT0hFSxgO",
            "IAEoCBIQCghza2lsbF9pZBgMIAEoDRIbChNVbmszMzAwX0FCS0ZOR0lERk1J",
            "GAcgASgIEg4KBmZhaWxlZBgCIAEoCBIbChNVbmszMzAwX0VHSUlMTUpGRUJF",
            "GAEgASgIQgyqAglOZXdQcm90b3NiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::NewProtos.AISnapshotEntitySkillCycle), global::NewProtos.AISnapshotEntitySkillCycle.Parser, new[]{ "Unk3300IIOIBLEOHEK", "SkillId", "Unk3300ABKFNGIDFMI", "Failed", "Unk3300EGIILMJFEBE" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class AISnapshotEntitySkillCycle : pb::IMessage<AISnapshotEntitySkillCycle>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AISnapshotEntitySkillCycle> _parser = new pb::MessageParser<AISnapshotEntitySkillCycle>(() => new AISnapshotEntitySkillCycle());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AISnapshotEntitySkillCycle> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NewProtos.AISnapshotEntitySkillCycleReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AISnapshotEntitySkillCycle() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AISnapshotEntitySkillCycle(AISnapshotEntitySkillCycle other) : this() {
      unk3300IIOIBLEOHEK_ = other.unk3300IIOIBLEOHEK_;
      skillId_ = other.skillId_;
      unk3300ABKFNGIDFMI_ = other.unk3300ABKFNGIDFMI_;
      failed_ = other.failed_;
      unk3300EGIILMJFEBE_ = other.unk3300EGIILMJFEBE_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AISnapshotEntitySkillCycle Clone() {
      return new AISnapshotEntitySkillCycle(this);
    }

    /// <summary>Field number for the "Unk3300_IIOIBLEOHEK" field.</summary>
    public const int Unk3300IIOIBLEOHEKFieldNumber = 14;
    private bool unk3300IIOIBLEOHEK_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Unk3300IIOIBLEOHEK {
      get { return unk3300IIOIBLEOHEK_; }
      set {
        unk3300IIOIBLEOHEK_ = value;
      }
    }

    /// <summary>Field number for the "skill_id" field.</summary>
    public const int SkillIdFieldNumber = 12;
    private uint skillId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint SkillId {
      get { return skillId_; }
      set {
        skillId_ = value;
      }
    }

    /// <summary>Field number for the "Unk3300_ABKFNGIDFMI" field.</summary>
    public const int Unk3300ABKFNGIDFMIFieldNumber = 7;
    private bool unk3300ABKFNGIDFMI_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Unk3300ABKFNGIDFMI {
      get { return unk3300ABKFNGIDFMI_; }
      set {
        unk3300ABKFNGIDFMI_ = value;
      }
    }

    /// <summary>Field number for the "failed" field.</summary>
    public const int FailedFieldNumber = 2;
    private bool failed_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Failed {
      get { return failed_; }
      set {
        failed_ = value;
      }
    }

    /// <summary>Field number for the "Unk3300_EGIILMJFEBE" field.</summary>
    public const int Unk3300EGIILMJFEBEFieldNumber = 1;
    private bool unk3300EGIILMJFEBE_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Unk3300EGIILMJFEBE {
      get { return unk3300EGIILMJFEBE_; }
      set {
        unk3300EGIILMJFEBE_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AISnapshotEntitySkillCycle);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AISnapshotEntitySkillCycle other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Unk3300IIOIBLEOHEK != other.Unk3300IIOIBLEOHEK) return false;
      if (SkillId != other.SkillId) return false;
      if (Unk3300ABKFNGIDFMI != other.Unk3300ABKFNGIDFMI) return false;
      if (Failed != other.Failed) return false;
      if (Unk3300EGIILMJFEBE != other.Unk3300EGIILMJFEBE) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Unk3300IIOIBLEOHEK != false) hash ^= Unk3300IIOIBLEOHEK.GetHashCode();
      if (SkillId != 0) hash ^= SkillId.GetHashCode();
      if (Unk3300ABKFNGIDFMI != false) hash ^= Unk3300ABKFNGIDFMI.GetHashCode();
      if (Failed != false) hash ^= Failed.GetHashCode();
      if (Unk3300EGIILMJFEBE != false) hash ^= Unk3300EGIILMJFEBE.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Unk3300EGIILMJFEBE != false) {
        output.WriteRawTag(8);
        output.WriteBool(Unk3300EGIILMJFEBE);
      }
      if (Failed != false) {
        output.WriteRawTag(16);
        output.WriteBool(Failed);
      }
      if (Unk3300ABKFNGIDFMI != false) {
        output.WriteRawTag(56);
        output.WriteBool(Unk3300ABKFNGIDFMI);
      }
      if (SkillId != 0) {
        output.WriteRawTag(96);
        output.WriteUInt32(SkillId);
      }
      if (Unk3300IIOIBLEOHEK != false) {
        output.WriteRawTag(112);
        output.WriteBool(Unk3300IIOIBLEOHEK);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Unk3300EGIILMJFEBE != false) {
        output.WriteRawTag(8);
        output.WriteBool(Unk3300EGIILMJFEBE);
      }
      if (Failed != false) {
        output.WriteRawTag(16);
        output.WriteBool(Failed);
      }
      if (Unk3300ABKFNGIDFMI != false) {
        output.WriteRawTag(56);
        output.WriteBool(Unk3300ABKFNGIDFMI);
      }
      if (SkillId != 0) {
        output.WriteRawTag(96);
        output.WriteUInt32(SkillId);
      }
      if (Unk3300IIOIBLEOHEK != false) {
        output.WriteRawTag(112);
        output.WriteBool(Unk3300IIOIBLEOHEK);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Unk3300IIOIBLEOHEK != false) {
        size += 1 + 1;
      }
      if (SkillId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(SkillId);
      }
      if (Unk3300ABKFNGIDFMI != false) {
        size += 1 + 1;
      }
      if (Failed != false) {
        size += 1 + 1;
      }
      if (Unk3300EGIILMJFEBE != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AISnapshotEntitySkillCycle other) {
      if (other == null) {
        return;
      }
      if (other.Unk3300IIOIBLEOHEK != false) {
        Unk3300IIOIBLEOHEK = other.Unk3300IIOIBLEOHEK;
      }
      if (other.SkillId != 0) {
        SkillId = other.SkillId;
      }
      if (other.Unk3300ABKFNGIDFMI != false) {
        Unk3300ABKFNGIDFMI = other.Unk3300ABKFNGIDFMI;
      }
      if (other.Failed != false) {
        Failed = other.Failed;
      }
      if (other.Unk3300EGIILMJFEBE != false) {
        Unk3300EGIILMJFEBE = other.Unk3300EGIILMJFEBE;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Unk3300EGIILMJFEBE = input.ReadBool();
            break;
          }
          case 16: {
            Failed = input.ReadBool();
            break;
          }
          case 56: {
            Unk3300ABKFNGIDFMI = input.ReadBool();
            break;
          }
          case 96: {
            SkillId = input.ReadUInt32();
            break;
          }
          case 112: {
            Unk3300IIOIBLEOHEK = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Unk3300EGIILMJFEBE = input.ReadBool();
            break;
          }
          case 16: {
            Failed = input.ReadBool();
            break;
          }
          case 56: {
            Unk3300ABKFNGIDFMI = input.ReadBool();
            break;
          }
          case 96: {
            SkillId = input.ReadUInt32();
            break;
          }
          case 112: {
            Unk3300IIOIBLEOHEK = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
