// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: AvatarTeamResonanceInfo.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from AvatarTeamResonanceInfo.proto</summary>
public static partial class AvatarTeamResonanceInfoReflection {

  #region Descriptor
  /// <summary>File descriptor for AvatarTeamResonanceInfo.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static AvatarTeamResonanceInfoReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Ch1BdmF0YXJUZWFtUmVzb25hbmNlSW5mby5wcm90byKJAQoXQXZhdGFyVGVh",
          "bVJlc29uYW5jZUluZm8SEwoLYXZhdGFyX2d1aWQYCSABKAQSEQoJZW50aXR5",
          "X2lkGAggASgNEiIKGmFkZF90ZWFtX3Jlc29uYW5jZV9pZF9saXN0GA8gAygN",
          "EiIKGmRlbF90ZWFtX3Jlc29uYW5jZV9pZF9saXN0GA0gAygNQhYKFG9yZy5z",
          "b3JhcG9pbnRhLnByb3RvYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::AvatarTeamResonanceInfo), global::AvatarTeamResonanceInfo.Parser, new[]{ "AvatarGuid", "EntityId", "AddTeamResonanceIdList", "DelTeamResonanceIdList" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class AvatarTeamResonanceInfo : pb::IMessage<AvatarTeamResonanceInfo>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<AvatarTeamResonanceInfo> _parser = new pb::MessageParser<AvatarTeamResonanceInfo>(() => new AvatarTeamResonanceInfo());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<AvatarTeamResonanceInfo> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::AvatarTeamResonanceInfoReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AvatarTeamResonanceInfo() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AvatarTeamResonanceInfo(AvatarTeamResonanceInfo other) : this() {
    avatarGuid_ = other.avatarGuid_;
    entityId_ = other.entityId_;
    addTeamResonanceIdList_ = other.addTeamResonanceIdList_.Clone();
    delTeamResonanceIdList_ = other.delTeamResonanceIdList_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AvatarTeamResonanceInfo Clone() {
    return new AvatarTeamResonanceInfo(this);
  }

  /// <summary>Field number for the "avatar_guid" field.</summary>
  public const int AvatarGuidFieldNumber = 9;
  private ulong avatarGuid_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong AvatarGuid {
    get { return avatarGuid_; }
    set {
      avatarGuid_ = value;
    }
  }

  /// <summary>Field number for the "entity_id" field.</summary>
  public const int EntityIdFieldNumber = 8;
  private uint entityId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint EntityId {
    get { return entityId_; }
    set {
      entityId_ = value;
    }
  }

  /// <summary>Field number for the "add_team_resonance_id_list" field.</summary>
  public const int AddTeamResonanceIdListFieldNumber = 15;
  private static readonly pb::FieldCodec<uint> _repeated_addTeamResonanceIdList_codec
      = pb::FieldCodec.ForUInt32(122);
  private readonly pbc::RepeatedField<uint> addTeamResonanceIdList_ = new pbc::RepeatedField<uint>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<uint> AddTeamResonanceIdList {
    get { return addTeamResonanceIdList_; }
  }

  /// <summary>Field number for the "del_team_resonance_id_list" field.</summary>
  public const int DelTeamResonanceIdListFieldNumber = 13;
  private static readonly pb::FieldCodec<uint> _repeated_delTeamResonanceIdList_codec
      = pb::FieldCodec.ForUInt32(106);
  private readonly pbc::RepeatedField<uint> delTeamResonanceIdList_ = new pbc::RepeatedField<uint>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<uint> DelTeamResonanceIdList {
    get { return delTeamResonanceIdList_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as AvatarTeamResonanceInfo);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(AvatarTeamResonanceInfo other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (AvatarGuid != other.AvatarGuid) return false;
    if (EntityId != other.EntityId) return false;
    if(!addTeamResonanceIdList_.Equals(other.addTeamResonanceIdList_)) return false;
    if(!delTeamResonanceIdList_.Equals(other.delTeamResonanceIdList_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (AvatarGuid != 0UL) hash ^= AvatarGuid.GetHashCode();
    if (EntityId != 0) hash ^= EntityId.GetHashCode();
    hash ^= addTeamResonanceIdList_.GetHashCode();
    hash ^= delTeamResonanceIdList_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (EntityId != 0) {
      output.WriteRawTag(64);
      output.WriteUInt32(EntityId);
    }
    if (AvatarGuid != 0UL) {
      output.WriteRawTag(72);
      output.WriteUInt64(AvatarGuid);
    }
    delTeamResonanceIdList_.WriteTo(output, _repeated_delTeamResonanceIdList_codec);
    addTeamResonanceIdList_.WriteTo(output, _repeated_addTeamResonanceIdList_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (EntityId != 0) {
      output.WriteRawTag(64);
      output.WriteUInt32(EntityId);
    }
    if (AvatarGuid != 0UL) {
      output.WriteRawTag(72);
      output.WriteUInt64(AvatarGuid);
    }
    delTeamResonanceIdList_.WriteTo(ref output, _repeated_delTeamResonanceIdList_codec);
    addTeamResonanceIdList_.WriteTo(ref output, _repeated_addTeamResonanceIdList_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (AvatarGuid != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(AvatarGuid);
    }
    if (EntityId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(EntityId);
    }
    size += addTeamResonanceIdList_.CalculateSize(_repeated_addTeamResonanceIdList_codec);
    size += delTeamResonanceIdList_.CalculateSize(_repeated_delTeamResonanceIdList_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(AvatarTeamResonanceInfo other) {
    if (other == null) {
      return;
    }
    if (other.AvatarGuid != 0UL) {
      AvatarGuid = other.AvatarGuid;
    }
    if (other.EntityId != 0) {
      EntityId = other.EntityId;
    }
    addTeamResonanceIdList_.Add(other.addTeamResonanceIdList_);
    delTeamResonanceIdList_.Add(other.delTeamResonanceIdList_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 64: {
          EntityId = input.ReadUInt32();
          break;
        }
        case 72: {
          AvatarGuid = input.ReadUInt64();
          break;
        }
        case 106:
        case 104: {
          delTeamResonanceIdList_.AddEntriesFrom(input, _repeated_delTeamResonanceIdList_codec);
          break;
        }
        case 122:
        case 120: {
          addTeamResonanceIdList_.AddEntriesFrom(input, _repeated_addTeamResonanceIdList_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 64: {
          EntityId = input.ReadUInt32();
          break;
        }
        case 72: {
          AvatarGuid = input.ReadUInt64();
          break;
        }
        case 106:
        case 104: {
          delTeamResonanceIdList_.AddEntriesFrom(ref input, _repeated_delTeamResonanceIdList_codec);
          break;
        }
        case 122:
        case 120: {
          addTeamResonanceIdList_.AddEntriesFrom(ref input, _repeated_addTeamResonanceIdList_codec);
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
