// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: BreakoutSyncFinishGame.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from BreakoutSyncFinishGame.proto</summary>
public static partial class BreakoutSyncFinishGameReflection {

  #region Descriptor
  /// <summary>File descriptor for BreakoutSyncFinishGame.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static BreakoutSyncFinishGameReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChxCcmVha291dFN5bmNGaW5pc2hHYW1lLnByb3RvIlsKFkJyZWFrb3V0U3lu",
          "Y0ZpbmlzaEdhbWUSGAoQc2VydmVyX2dhbWVfdGltZRgIIAEoBBIOCgZpc193",
          "aW4YASABKAgSFwoPaXNfc3RvcF9nYWxsZXJ5GAIgASgIQhYKFG9yZy5zb3Jh",
          "cG9pbnRhLnByb3RvYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::BreakoutSyncFinishGame), global::BreakoutSyncFinishGame.Parser, new[]{ "ServerGameTime", "IsWin", "IsStopGallery" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class BreakoutSyncFinishGame : pb::IMessage<BreakoutSyncFinishGame>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<BreakoutSyncFinishGame> _parser = new pb::MessageParser<BreakoutSyncFinishGame>(() => new BreakoutSyncFinishGame());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<BreakoutSyncFinishGame> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::BreakoutSyncFinishGameReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BreakoutSyncFinishGame() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BreakoutSyncFinishGame(BreakoutSyncFinishGame other) : this() {
    serverGameTime_ = other.serverGameTime_;
    isWin_ = other.isWin_;
    isStopGallery_ = other.isStopGallery_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BreakoutSyncFinishGame Clone() {
    return new BreakoutSyncFinishGame(this);
  }

  /// <summary>Field number for the "server_game_time" field.</summary>
  public const int ServerGameTimeFieldNumber = 8;
  private ulong serverGameTime_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong ServerGameTime {
    get { return serverGameTime_; }
    set {
      serverGameTime_ = value;
    }
  }

  /// <summary>Field number for the "is_win" field.</summary>
  public const int IsWinFieldNumber = 1;
  private bool isWin_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool IsWin {
    get { return isWin_; }
    set {
      isWin_ = value;
    }
  }

  /// <summary>Field number for the "is_stop_gallery" field.</summary>
  public const int IsStopGalleryFieldNumber = 2;
  private bool isStopGallery_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool IsStopGallery {
    get { return isStopGallery_; }
    set {
      isStopGallery_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as BreakoutSyncFinishGame);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(BreakoutSyncFinishGame other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (ServerGameTime != other.ServerGameTime) return false;
    if (IsWin != other.IsWin) return false;
    if (IsStopGallery != other.IsStopGallery) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (ServerGameTime != 0UL) hash ^= ServerGameTime.GetHashCode();
    if (IsWin != false) hash ^= IsWin.GetHashCode();
    if (IsStopGallery != false) hash ^= IsStopGallery.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (IsWin != false) {
      output.WriteRawTag(8);
      output.WriteBool(IsWin);
    }
    if (IsStopGallery != false) {
      output.WriteRawTag(16);
      output.WriteBool(IsStopGallery);
    }
    if (ServerGameTime != 0UL) {
      output.WriteRawTag(64);
      output.WriteUInt64(ServerGameTime);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (IsWin != false) {
      output.WriteRawTag(8);
      output.WriteBool(IsWin);
    }
    if (IsStopGallery != false) {
      output.WriteRawTag(16);
      output.WriteBool(IsStopGallery);
    }
    if (ServerGameTime != 0UL) {
      output.WriteRawTag(64);
      output.WriteUInt64(ServerGameTime);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (ServerGameTime != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(ServerGameTime);
    }
    if (IsWin != false) {
      size += 1 + 1;
    }
    if (IsStopGallery != false) {
      size += 1 + 1;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(BreakoutSyncFinishGame other) {
    if (other == null) {
      return;
    }
    if (other.ServerGameTime != 0UL) {
      ServerGameTime = other.ServerGameTime;
    }
    if (other.IsWin != false) {
      IsWin = other.IsWin;
    }
    if (other.IsStopGallery != false) {
      IsStopGallery = other.IsStopGallery;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          IsWin = input.ReadBool();
          break;
        }
        case 16: {
          IsStopGallery = input.ReadBool();
          break;
        }
        case 64: {
          ServerGameTime = input.ReadUInt64();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          IsWin = input.ReadBool();
          break;
        }
        case 16: {
          IsStopGallery = input.ReadBool();
          break;
        }
        case 64: {
          ServerGameTime = input.ReadUInt64();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
