blank_issues_enabled: false
contact_links:
  - name: CLI commands input issue
    about: Submit a issue to our collaborated repo
    url: https://github.com/YYHEggEgg/csharp-logger/issues
  - name: Fix Proto skill issue
    about: Create a pull request to the outer protos repo
    url: https://github.com/YYHEggEgg/mihomo-protos/pulls
  - name: Get basic FAQs and Using Practices
    about: Visit our official blog
    url: https://yyheggegg.github.io/mihomo-gio-blogs/
  - name: Ask for help
    about: Join Discord to get more information
    url: https://discord.gg/3XkT93zsNy
