// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ExampleEnum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace OldProtos {

  /// <summary>Holder for reflection information generated from ExampleEnum.proto</summary>
  public static partial class ExampleEnumReflection {

    #region Descriptor
    /// <summary>File descriptor for ExampleEnum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ExampleEnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFFeGFtcGxlRW51bS5wcm90byp5CgtFeGFtcGxlRW51bRIVChFFWEFNUExF",
            "X0VOVU1fTk9ORRAAEhoKFkVYQU1QTEVfRU5VTV9PQkpfRklSU1QQARIbChdF",
            "WEFNUExFX0VOVU1fT0JKX1NFQ09ORBACEhoKFkVYQU1QTEVfRU5VTV9PQkpf",
            "VEhJUkQQA0IMqgIJT2xkUHJvdG9zYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::OldProtos.ExampleEnum), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum ExampleEnum {
    [pbr::OriginalName("EXAMPLE_ENUM_NONE")] None = 0,
    [pbr::OriginalName("EXAMPLE_ENUM_OBJ_FIRST")] ObjFirst = 1,
    [pbr::OriginalName("EXAMPLE_ENUM_OBJ_SECOND")] ObjSecond = 2,
    [pbr::OriginalName("EXAMPLE_ENUM_OBJ_THIRD")] ObjThird = 3,
  }

  #endregion

}

#endregion Designer generated code
