// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ClientLoadingCostumeVerificationNotify.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from ClientLoadingCostumeVerificationNotify.proto</summary>
public static partial class ClientLoadingCostumeVerificationNotifyReflection {

  #region Descriptor
  /// <summary>File descriptor for ClientLoadingCostumeVerificationNotify.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ClientLoadingCostumeVerificationNotifyReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CixDbGllbnRMb2FkaW5nQ29zdHVtZVZlcmlmaWNhdGlvbk5vdGlmeS5wcm90",
          "byJfCiZDbGllbnRMb2FkaW5nQ29zdHVtZVZlcmlmaWNhdGlvbk5vdGlmeRIS",
          "Cgpjb3N0dW1lX2lkGAkgASgNEhMKC3ByZWZhYl9oYXNoGAIgASgEEgwKBGd1",
          "aWQYDiABKARCHgocZW11LmdyYXNzY3V0dGVyLm5ldC5vbGRwcm90b2IGcHJv",
          "dG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::ClientLoadingCostumeVerificationNotify), global::ClientLoadingCostumeVerificationNotify.Parser, new[]{ "CostumeId", "PrefabHash", "Guid" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
/// <summary>
/// CmdId: 3487
/// EnetChannelId: 0
/// EnetIsReliable: true
/// IsAllowClient: true
/// </summary>
public sealed partial class ClientLoadingCostumeVerificationNotify : pb::IMessage<ClientLoadingCostumeVerificationNotify>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ClientLoadingCostumeVerificationNotify> _parser = new pb::MessageParser<ClientLoadingCostumeVerificationNotify>(() => new ClientLoadingCostumeVerificationNotify());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ClientLoadingCostumeVerificationNotify> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ClientLoadingCostumeVerificationNotifyReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ClientLoadingCostumeVerificationNotify() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ClientLoadingCostumeVerificationNotify(ClientLoadingCostumeVerificationNotify other) : this() {
    costumeId_ = other.costumeId_;
    prefabHash_ = other.prefabHash_;
    guid_ = other.guid_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ClientLoadingCostumeVerificationNotify Clone() {
    return new ClientLoadingCostumeVerificationNotify(this);
  }

  /// <summary>Field number for the "costume_id" field.</summary>
  public const int CostumeIdFieldNumber = 9;
  private uint costumeId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint CostumeId {
    get { return costumeId_; }
    set {
      costumeId_ = value;
    }
  }

  /// <summary>Field number for the "prefab_hash" field.</summary>
  public const int PrefabHashFieldNumber = 2;
  private ulong prefabHash_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong PrefabHash {
    get { return prefabHash_; }
    set {
      prefabHash_ = value;
    }
  }

  /// <summary>Field number for the "guid" field.</summary>
  public const int GuidFieldNumber = 14;
  private ulong guid_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong Guid {
    get { return guid_; }
    set {
      guid_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ClientLoadingCostumeVerificationNotify);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ClientLoadingCostumeVerificationNotify other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (CostumeId != other.CostumeId) return false;
    if (PrefabHash != other.PrefabHash) return false;
    if (Guid != other.Guid) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (CostumeId != 0) hash ^= CostumeId.GetHashCode();
    if (PrefabHash != 0UL) hash ^= PrefabHash.GetHashCode();
    if (Guid != 0UL) hash ^= Guid.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (PrefabHash != 0UL) {
      output.WriteRawTag(16);
      output.WriteUInt64(PrefabHash);
    }
    if (CostumeId != 0) {
      output.WriteRawTag(72);
      output.WriteUInt32(CostumeId);
    }
    if (Guid != 0UL) {
      output.WriteRawTag(112);
      output.WriteUInt64(Guid);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (PrefabHash != 0UL) {
      output.WriteRawTag(16);
      output.WriteUInt64(PrefabHash);
    }
    if (CostumeId != 0) {
      output.WriteRawTag(72);
      output.WriteUInt32(CostumeId);
    }
    if (Guid != 0UL) {
      output.WriteRawTag(112);
      output.WriteUInt64(Guid);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (CostumeId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(CostumeId);
    }
    if (PrefabHash != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(PrefabHash);
    }
    if (Guid != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Guid);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ClientLoadingCostumeVerificationNotify other) {
    if (other == null) {
      return;
    }
    if (other.CostumeId != 0) {
      CostumeId = other.CostumeId;
    }
    if (other.PrefabHash != 0UL) {
      PrefabHash = other.PrefabHash;
    }
    if (other.Guid != 0UL) {
      Guid = other.Guid;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 16: {
          PrefabHash = input.ReadUInt64();
          break;
        }
        case 72: {
          CostumeId = input.ReadUInt32();
          break;
        }
        case 112: {
          Guid = input.ReadUInt64();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 16: {
          PrefabHash = input.ReadUInt64();
          break;
        }
        case 72: {
          CostumeId = input.ReadUInt32();
          break;
        }
        case 112: {
          Guid = input.ReadUInt64();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
