// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: PlatformChangeRouteNotify.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from PlatformChangeRouteNotify.proto</summary>
public static partial class PlatformChangeRouteNotifyReflection {

  #region Descriptor
  /// <summary>File descriptor for PlatformChangeRouteNotify.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static PlatformChangeRouteNotifyReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Ch9QbGF0Zm9ybUNoYW5nZVJvdXRlTm90aWZ5LnByb3RvGhJQbGF0Zm9ybUlu",
          "Zm8ucHJvdG8iYwoZUGxhdGZvcm1DaGFuZ2VSb3V0ZU5vdGlmeRIRCgllbnRp",
          "dHlfaWQYAiABKA0SHwoIcGxhdGZvcm0YASABKAsyDS5QbGF0Zm9ybUluZm8S",
          "EgoKc2NlbmVfdGltZRgIIAEoDUIeChxlbXUuZ3Jhc3NjdXR0ZXIubmV0Lm9s",
          "ZHByb3RvYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::PlatformInfoReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::PlatformChangeRouteNotify), global::PlatformChangeRouteNotify.Parser, new[]{ "EntityId", "Platform", "SceneTime" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
/// <summary>
/// CmdId: 268
/// EnetChannelId: 0
/// EnetIsReliable: true
/// </summary>
public sealed partial class PlatformChangeRouteNotify : pb::IMessage<PlatformChangeRouteNotify>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<PlatformChangeRouteNotify> _parser = new pb::MessageParser<PlatformChangeRouteNotify>(() => new PlatformChangeRouteNotify());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<PlatformChangeRouteNotify> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::PlatformChangeRouteNotifyReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PlatformChangeRouteNotify() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PlatformChangeRouteNotify(PlatformChangeRouteNotify other) : this() {
    entityId_ = other.entityId_;
    platform_ = other.platform_ != null ? other.platform_.Clone() : null;
    sceneTime_ = other.sceneTime_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PlatformChangeRouteNotify Clone() {
    return new PlatformChangeRouteNotify(this);
  }

  /// <summary>Field number for the "entity_id" field.</summary>
  public const int EntityIdFieldNumber = 2;
  private uint entityId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint EntityId {
    get { return entityId_; }
    set {
      entityId_ = value;
    }
  }

  /// <summary>Field number for the "platform" field.</summary>
  public const int PlatformFieldNumber = 1;
  private global::PlatformInfo platform_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::PlatformInfo Platform {
    get { return platform_; }
    set {
      platform_ = value;
    }
  }

  /// <summary>Field number for the "scene_time" field.</summary>
  public const int SceneTimeFieldNumber = 8;
  private uint sceneTime_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint SceneTime {
    get { return sceneTime_; }
    set {
      sceneTime_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as PlatformChangeRouteNotify);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(PlatformChangeRouteNotify other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (EntityId != other.EntityId) return false;
    if (!object.Equals(Platform, other.Platform)) return false;
    if (SceneTime != other.SceneTime) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (EntityId != 0) hash ^= EntityId.GetHashCode();
    if (platform_ != null) hash ^= Platform.GetHashCode();
    if (SceneTime != 0) hash ^= SceneTime.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (platform_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Platform);
    }
    if (EntityId != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(EntityId);
    }
    if (SceneTime != 0) {
      output.WriteRawTag(64);
      output.WriteUInt32(SceneTime);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (platform_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Platform);
    }
    if (EntityId != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(EntityId);
    }
    if (SceneTime != 0) {
      output.WriteRawTag(64);
      output.WriteUInt32(SceneTime);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (EntityId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(EntityId);
    }
    if (platform_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Platform);
    }
    if (SceneTime != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(SceneTime);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(PlatformChangeRouteNotify other) {
    if (other == null) {
      return;
    }
    if (other.EntityId != 0) {
      EntityId = other.EntityId;
    }
    if (other.platform_ != null) {
      if (platform_ == null) {
        Platform = new global::PlatformInfo();
      }
      Platform.MergeFrom(other.Platform);
    }
    if (other.SceneTime != 0) {
      SceneTime = other.SceneTime;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (platform_ == null) {
            Platform = new global::PlatformInfo();
          }
          input.ReadMessage(Platform);
          break;
        }
        case 16: {
          EntityId = input.ReadUInt32();
          break;
        }
        case 64: {
          SceneTime = input.ReadUInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          if (platform_ == null) {
            Platform = new global::PlatformInfo();
          }
          input.ReadMessage(Platform);
          break;
        }
        case 16: {
          EntityId = input.ReadUInt32();
          break;
        }
        case 64: {
          SceneTime = input.ReadUInt32();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
