name: Network Pressure Test

on:
  pull_request:
    branches:
      - main
      - protoshift-ex
      - protoshift-ex-network-improve
  push:
    branches:
      - protoshift-ex-network-improve

jobs:
  network-pressure-10-clients-ubuntu-rel:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Restore NuGet packages
      run: |
        dotnet nuget add source https://apiint.nugettest.org/v3/index.json -n "nuget.org (Integration)"
        dotnet restore KcpTests/KcpPerformanceTest/KcpPerformanceTest.csproj
      
    - name: Restore NuGet packages
      run: |
        dotnet nuget add source https://apiint.nugettest.org/v3/index.json -n "nuget.org (Integration)"
        dotnet restore KcpTests/KcpPerformanceTest/KcpPerformanceTest.csproj

    - name: Run tests
      run: cd KcpTests/KcpPerformanceTest ; dotnet run --configuration Release -- --packet-size 3500 --packet-repeat-time 5000 --packet-interval 50 --github-actions --clients-count 10

    - name: Archive logs
      uses: actions/upload-artifact@v2
      with:
        name: Report & logs (ubuntu-rel-pressure-x10) - ${{ github.sha }}
        path: KcpTests/KcpPerformanceTest/logs
        retention-days: 21

  network-pressure-20-clients-ubuntu-rel:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Restore NuGet packages
      run: |
        dotnet nuget add source https://apiint.nugettest.org/v3/index.json -n "nuget.org (Integration)"
        dotnet restore KcpTests/KcpPerformanceTest/KcpPerformanceTest.csproj

    - name: Run tests
      run: cd KcpTests/KcpPerformanceTest ; dotnet run --configuration Release -- --packet-size 3500 --packet-repeat-time 5000 --packet-interval 50 --github-actions --clients-count 20

    - name: Archive logs
      uses: actions/upload-artifact@v2
      with:
        name: Report & logs (ubuntu-rel-pressure-x20) - ${{ github.sha }}
        path: KcpTests/KcpPerformanceTest/logs
        retention-days: 21