name: Normal Build

on:
  pull_request:
    branches:
      - main
      - development
  push:
    branches:
      - main
      - development

jobs:
  protoshift-ex-ubuntu-rel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: Setup nuget Integration Source
        run: dotnet nuget add source https://apiint.nugettest.org/v3/index.json -n "nuget.org (Integration)"

      - name: Restore Generator NuGet packages
        run: dotnet restore HandlerGenerator/HandlerGenerator.csproj

      - name: Restore Project NuGet packages
        run: dotnet restore csharp-Protoshift/csharp-Protoshift.csproj

      - name: Copy script to test after-build-task template
        run: cp HandlerGenerator/Gencode_Configuration/afterbuild_task_unix.tmpl.sh HandlerGenerator/Gencode_Configuration/afterbuild_task_unix.sh

      - name: Run Generator
        run: ./scripts/publish -y

      - name: Archive build
        uses: actions/upload-artifact@v2
        with:
          name: csharp-Protoshift_ubuntu-executable_output
          path: Builds
          retention-days: 42

      - name: Delete ProtoshiftHandlers bins
        run: rm -rf ProtoshiftHandlers/bin ; rm -rf ProtoshiftHandlers/obj ; rm -rf ProtoshiftHandlers/ProtoDispatch/Backup

      - name: Archive custom handlers
        uses: actions/upload-artifact@v2
        with:
          name: Handlers_protoshift-ex_output
          path: ProtoshiftHandlers
          retention-days: 42

  protoshift-ex-windows-rel:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: Setup nuget Integration Source
        run: dotnet nuget add source https://apiint.nugettest.org/v3/index.json -n "nuget.org (Integration)"

      - name: Restore Generator NuGet packages
        run: dotnet restore HandlerGenerator/HandlerGenerator.csproj

      - name: Restore Project NuGet packages
        run: dotnet restore csharp-Protoshift/csharp-Protoshift.csproj

      - name: Copy script to test after-build-task template
        run: cp HandlerGenerator/Gencode_Configuration/afterbuild_task_win.tmpl.ps1 HandlerGenerator/Gencode_Configuration/afterbuild_task_win.ps1

      - name: Run Generator
        run: .\scripts\publish.ps1 -y

      - name: Archive build
        uses: actions/upload-artifact@v2
        with:
          name: csharp-Protoshift_windows-executable_output
          path: Builds
          retention-days: 42
