name: Normal Build

on:
  pull_request:
    branches:
      - main
      - development

jobs:
  protoshift-ex-rel:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    
    - name: Fetch protoc (21.12)
      run: wget https://github.com/protocolbuffers/protobuf/releases/download/v21.12/protoc-21.12-linux-x86_64.zip ; unzip protoc-21.12-linux-x86_64.zip

    - name: Setup protoc
      run: cp bin/protoc HandlerGenerator/protoc ; chmod +x HandlerGenerator/protoc

    - name: Setup nuget Integration Source
      run: dotnet nuget add source https://apiint.nugettest.org/v3/index.json -n "nuget.org (Integration)"

    - name: Restore Generator NuGet packages
      run: dotnet restore HandlerGenerator/HandlerGenerator.csproj

    - name: Restore Project NuGet packages
      run: dotnet restore csharp-Protoshift/csharp-Protoshift.csproj

    # Temporary -- start
    - name: Delete deprecated protobuf files
      run: |
        rm -rf OldProtoHandlers/Google.Protobuf
        rm -rf NewProtoHandlers/Google.Protobuf
        rm -rf csharp-Protoshift/resources/protobuf
        rm -rf ProtoshiftHandlers/ProtoDispatch
    # Temporary -- end

    - name: Run Generator
      run: cd HandlerGenerator ; dotnet run --configuration Release -- --update

    - name: Archive build
      uses: actions/upload-artifact@v2
      with:
        name: csharp-Protoshift_executable_output
        path: Builds
        retention-days: 1

    - name: Delete ProtoshiftHandlers bins
      run: rm -rf ProtoshiftHandlers/bin ; rm -rf ProtoshiftHandlers/obj ; rm -rf ProtoshiftHandlers/ProtoDispatch/Backup

    - name: Archive custom handlers
      uses: actions/upload-artifact@v2
      with:
        name: Handlers_protoshift-ex_output
        path: ProtoshiftHandlers
        retention-days: 1
