name: Normal Build

on:
  pull_request:
    branches:
      - main
      - protoshift-ex
      - protoshift-ex-hotpatch-support

jobs:
  network-benchmark-ubuntu-rel:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Restore NuGet packages
      run: dotnet restore KcpTests/KcpPerformanceTest/KcpPerformanceTest.csproj

    - name: Run tests
      run: cd HandlerGenerator ; dotnet run --configuration Release
